name: Publish
run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish Unity SDK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        if: false
        uses: actions/checkout@v3

      - name: Version Tag
        id: version_tag
        run: |
          echo Version: ${GITHUB_REF_NAME}
          echo "VERSION=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

      - name: Release
        if: ${{ !contains(github.event.ref, '-') }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Affise Attribution Unity SDK ${{ github.ref }}
          draft: false
          prerelease: false
